[project]
name = "SouthsideMusic"
version = "v47"
description = "Advanced music player"
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
    "colorama>=0.4.6",
    "darkdetect>=0.8.0",
    "hpyt>=1.4.0",
    "mutagen>=1.48.1",
    "numpy>=2.5.3",
    "onnxruntime==1.30.0",
    "pillow>=12.3.0",
    "pydub>=0.25.1",
    "psutil>=7.2.0",
    "pycryptodome>=3.23.0",
    "pyside6>=6.11.2",
    "pyside6-fluent-widgets>=1.11.3",
    "qrcode>=8.2",
    "requests>=2.34.2",
    "scipy>=1.18.1",
    "sounddevice>=0.5.6",
    "toml>=0.10.2",
    "tornado>=6.5.10",
    "tqdm>=4.70.1",
    "audioop-lts>=0.2.2",
    "openai<=3.22.1",
    "pywin32>=312",
    "anthropic>=1.11.0",
    "markdown-it-py>=3.0.0",
    "ziamath==0.13",
    "winrt-windows-media>=3.2.1",
    "winrt-windows-media-interop>=3.2.1",
    "winrt-windows-foundation>=3.2.1",
    "winrt-windows-storage-streams>=3.2.1",
    "scipy-stubs~=1.18.1",
]

[dependency-groups]
dev = [
    "ruff<=0.16.9",
    "mypy<=2.3.1",
]
