IMAGE_ASSET_PERSISTED = 'image_asset_persisted'
SONG_CHANGED = 'song_changed'
SONG_ENDED = 'song_ended'
PLAY_STATE_CHANGED = 'play_state_changed'
POST_THEME_CHANGED = 'post_theme_changed'
PRE_THEME_CHANGED = 'pre_theme_changed'
FAVORITES_CHANGED = 'favorites_changed'
WEBSOCKET_CONNECTED = 'websocket_connected'
WEBSOCKET_DISCONNECTED = 'websocket_disconnected'
LUFS_TARGET_CHANGED = 'lufs_target_changed'
LYRIC_LINE_CHANGED = 'lyric_line_changed'
REFRESH_RATE_CHANGED = 'refresh_rate_changed'
REPAINT = 'repaint'
UPDATE_FM = 'update_fm'
BACKGROUND_RATIO_CHANGED = 'background_ratio_changed'
VIEW_FOLDER = 'view_folder'

START_INTER_LOADING = 'start_inter_loading'
START_PROGRESS_LOADING = 'start_progress_loading'
STOP_INTER_LOADING = 'stop_inter_loading'
STOP_PROGRESS_LOADING = 'stop_progress_loading'
UPDATE_LOADING_PROGRESS = 'update_loading_progress'

ENDING_NO_SOUND = 'ending_no_sound'

SONG_FINISH = 'song_finish'
PLAYNEXT = 'playnext'
PLAYLAST = 'playlast'
