import json
import pickle
from pprint import pprint

import pyncm
import pyncm.apis

with open('config.pkl', 'rb') as f:
    data = pickle.load(f)

    pyncm.WriteLoginInfo(data['login_status'])
    pyncm.SetCurrentSession(pyncm.LoadSessionFromString(data['session']))

    with open('res.json', 'w') as f:
        f.write(json.dumps(pyncm.apis.track.GetTrackDetail(['518904426']), indent=4))

    # pprint(pyncm.apis.track.GetTrackLyricsNew('518904426'))

    # playlists = pyncm.apis.user.GetUserPlaylists(pyncm.GetCurrentSession().uid)['playlist'] # type: ignore
    # pprint(playlists)
    # pprint(pyncm.apis.playlist.GetPlaylistAllTracks(17923377465))

    # playlists = pyncm.apis.user.GetUserPlaylists(pyncm.GetCurrentSession().uid)['playlist'] # type: ignore
    # pprint(playlists)
    # =>
    #     [{'adType': 0,
    #   'anonimous': False,
    #   'artists': None,
    #   'backgroundCoverId': 0,
    #   'backgroundCoverUrl': None,
    #   'cloudTrackCount': 0,
    #   'commentThreadId': 'A_PL_0_13331336677',
    #   'containsTracks': False,
    #   'copied': False,
    #   'coverImgId': 109951165434984508,
    #   'coverImgId_str': '109951165434984508',
    #   'coverImgUrl': 'http://p1.music.126.net/9-rm4PUkKuL-lD1Rgg6SDw==/109951165434984508.jpg',
    #   'createTime': 1739700633510,
    #   'creator': {'accountStatus': 0,
    #               'anchor': False,
    #               'authStatus': 0,
    #               'authenticationTypes': 0,
    #               'authority': 0,
    #               'avatarDetail': None,
    #               'avatarImgId': 109951173088338954,
    #               'avatarImgIdStr': '109951173088338954',
    #               'avatarImgId_str': '109951173088338954',
    #               'avatarUrl': 'http://p1.music.126.net/_Ml-2_0Hb57m94acyCU9rQ==/109951173088338954.jpg',
    #               'backgroundImgId': 109951162868126486,
    #               'backgroundImgIdStr': '109951162868126486',
    #               'backgroundUrl': 'http://p1.music.126.net/_f8R60U9mZ42sSNvdPn2sQ==/109951162868126486.jpg',
    #               'birthday': 0,
    #               'city': 532500,
    #               'defaultAvatar': False,
    #               'description': '',
    #               'detailDescription': '',
    #               'djStatus': 0,
    #               'expertTags': None,
    #               'experts': None,
    #               'followed': False,
    #               'gender': 0,
    #               'mutual': False,
    #               'nickname': 'Adreno9135',
    #               'province': 530000,
    #               'remarkName': None,
    #               'signature': '',
    #               'userId': 13149209959,
    #               'userType': 0,
    #               'vipType': 11},
    #   'description': None,
    #   'englishTitle': None,
    #   'highQuality': False,
    #   'id': 13331336677,
    #   'name': 'Adreno9135喜欢的音乐',
    #   'newImported': False,
    #   'opRecommend': False,
    #   'ordered': False,
    #   'playCount': 0,
    #   'privacy': 0,
    #   'recommendInfo': None,
    #   'shareStatus': None,
    #   'sharedUsers': None,
    #   'specialType': 5,
    #   'status': 0,
    #   'subscribed': None,
    #   'subscribedCount': 0,
    #   'subscribers': [],
    #   'tags': [],
    #   'titleImage': 0,
    #   'titleImageUrl': None,
    #   'top': False,
    #   'totalDuration': 0,
    #   'trackCount': 0,
    #   'trackNumberUpdateTime': 1751034122747,
    #   'trackUpdateTime': 1751034124783,
    #   'tracks': None,
    #   'updateFrequency': None,
    #   'updateTime': 1751034124773,
    #   'userId': 13149209959},
    #  {'adType': 0,
    #   'anonimous': False,
    #   'artists': None,
    #   'backgroundCoverId': 0,
    #   'backgroundCoverUrl': None,
    #   'cloudTrackCount': 0,
    #   'commentThreadId': 'A_PL_0_17923377465',
    #   'containsTracks': False,
    #   'copied': False,
    #   'coverImgId': 18223305719326928,
    #   'coverImgId_str': '18223305719326928',
    #   'coverImgUrl': 'http://p1.music.126.net/5ChG4-2IkYzwnj2-WScvMw==/18223305719326928.jpg',
    #   'createTime': 1777105545097,
    #   'creator': {'accountStatus': 0,
    #               'anchor': False,
    #               'authStatus': 0,
    #               'authenticationTypes': 0,
    #               'authority': 0,
    #               'avatarDetail': None,
    #               'avatarImgId': 109951173088338954,
    #               'avatarImgIdStr': '109951173088338954',
    #               'avatarImgId_str': '109951173088338954',
    #               'avatarUrl': 'http://p1.music.126.net/_Ml-2_0Hb57m94acyCU9rQ==/109951173088338954.jpg',
    #               'backgroundImgId': 109951162868126486,
    #               'backgroundImgIdStr': '109951162868126486',
    #               'backgroundUrl': 'http://p1.music.126.net/_f8R60U9mZ42sSNvdPn2sQ==/109951162868126486.jpg',
    #               'birthday': 0,
    #               'city': 532500,
    #               'defaultAvatar': False,
    #               'description': '',
    #               'detailDescription': '',
    #               'djStatus': 0,
    #               'expertTags': None,
    #               'experts': None,
    #               'followed': False,
    #               'gender': 0,
    #               'mutual': False,
    #               'nickname': 'Adreno9135',
    #               'province': 530000,
    #               'remarkName': None,
    #               'signature': '',
    #               'userId': 13149209959,
    #               'userType': 0,
    #               'vipType': 11},
    #   'description': None,
    #   'englishTitle': None,
    #   'highQuality': False,
    #   'id': 17923377465,
    #   'name': 'Ilyove',
    #   'newImported': False,
    #   'opRecommend': False,
    #   'ordered': False,
    #   'playCount': 0,
    #   'privacy': 10,
    #   'recommendInfo': None,
    #   'shareStatus': None,
    #   'sharedUsers': None,
    #   'specialType': 0,
    #   'status': 0,
    #   'subscribed': None,
    #   'subscribedCount': 0,
    #   'subscribers': [],
    #   'tags': [],
    #   'titleImage': 0,
    #   'titleImageUrl': None,
    #   'top': False,
    #   'totalDuration': 0,
    #   'trackCount': 2,
    #   'trackNumberUpdateTime': 1777105731012,
    #   'trackUpdateTime': 1777105731208,
    #   'tracks': None,
    #   'updateFrequency': None,
    #   'updateTime': 1777105731012,
    #   'userId': 13149209959}]
    # pprint(pyncm.apis.playlist.GetPlaylistAllTracks(17923377465))
    # =>
    # {'code': 200,
    #  'privileges': [{'bd': None,
    #                  'chargeInfoList': [{'chargeMessage': None,
    #                                      'chargeType': 1,
    #                                      'chargeUrl': None,
    #                                      'rate': 128000},
    #                                     {'chargeMessage': None,
    #                                      'chargeType': 1,
    #                                      'chargeUrl': None,
    #                                      'rate': 192000},
    #                                     {'chargeMessage': None,
    #                                      'chargeType': 1,
    #                                      'chargeUrl': None,
    #                                      'rate': 320000},
    #                                     {'chargeMessage': None,
    #                                      'chargeType': 1,
    #                                      'chargeUrl': None,
    #                                      'rate': 999000}],
    #                  'code': 0,
    #                  'cp': 1,
    #                  'cs': False,
    #                  'dl': 999000,
    #                  'dlLevel': 'jyeffect',
    #                  'dlLevels': None,
    #                  'downloadMaxBrLevel': 'vivid',
    #                  'downloadMaxbr': 999000,
    #                  'fee': 1,
    #                  'fl': 0,
    #                  'flLevel': 'none',
    #                  'flag': 4161540,
    #                  'freeTrialPrivilege': {'cannotListenReason': None,
    #                                         'freeLimitTagType': None,
    #                                         'listenType': None,
    #                                         'playReason': None,
    #                                         'resConsumable': False,
    #                                         'userConsumable': False},
    #                  'id': 508671230,
    #                  'ignoreCache': None,
    #                  'maxBrLevel': 'vivid',
    #                  'maxbr': 999000,
    #                  'message': None,
    #                  'payed': 1,
    #                  'pl': 999000,
    #                  'plLevel': 'jyeffect',
    #                  'plLevels': None,
    #                  'playMaxBrLevel': 'vivid',
    #                  'playMaxbr': 999000,
    #                  'preSell': False,
    #                  'rightSource': 0,
    #                  'rscl': None,
    #                  'sp': 7,
    #                  'st': 0,
    #                  'subp': 1,
    #                  'toast': False},
    #                 {'bd': None,
    #                  'chargeInfoList': [{'chargeMessage': None,
    #                                      'chargeType': 1,
    #                                      'chargeUrl': None,
    #                                      'rate': 128000},
    #                                     {'chargeMessage': None,
    #                                      'chargeType': 1,
    #                                      'chargeUrl': None,
    #                                      'rate': 192000},
    #                                     {'chargeMessage': None,
    #                                      'chargeType': 1,
    #                                      'chargeUrl': None,
    #                                      'rate': 320000},
    #                                     {'chargeMessage': None,
    #                                      'chargeType': 1,
    #                                      'chargeUrl': None,
    #                                      'rate': 999000}],
    #                  'code': 0,
    #                  'cp': 1,
    #                  'cs': False,
    #                  'dl': 999000,
    #                  'dlLevel': 'jyeffect',
    #                  'dlLevels': None,
    #                  'downloadMaxBrLevel': 'vivid',
    #                  'downloadMaxbr': 999000,
    #                  'fee': 1,
    #                  'fl': 0,
    #                  'flLevel': 'none',
    #                  'flag': 4161540,
    #                  'freeTrialPrivilege': {'cannotListenReason': None,
    #                                         'freeLimitTagType': None,
    #                                         'listenType': None,
    #                                         'playReason': None,
    #                                         'resConsumable': False,
    #                                         'userConsumable': False},
    #                  'id': 28694864,
    #                  'ignoreCache': None,
    #                  'maxBrLevel': 'vivid',
    #                  'maxbr': 999000,
    #                  'message': None,
    #                  'payed': 1,
    #                  'pl': 999000,
    #                  'plLevel': 'jyeffect',
    #                  'plLevels': None,
    #                  'playMaxBrLevel': 'vivid',
    #                  'playMaxbr': 999000,
    #                  'preSell': False,
    #                  'rightSource': 0,
    #                  'rscl': None,
    #                  'sp': 7,
    #                  'st': 0,
    #                  'subp': 1,
    #                  'toast': False}],
    #  'songs': [{'a': None,
    #             'additionalTitle': '(Original Mix)',
    #             'al': {'id': 36383914,
    #                    'name': 'Peeping Tom',
    #                    'pic': 18223305719326928,
    #                    'picUrl': 'https://p2.music.126.net/5ChG4-2IkYzwnj2-WScvMw==/18223305719326928.jpg',
    #                    'pic_str': '18223305719326928',
    #                    'tns': []},
    #             'alia': [],
    #             'ar': [{'alias': [],
    #                     'id': 336234,
    #                     'name': 'Jamie Berry',
    #                     'tns': []},
    #                    {'alias': [],
    #                     'id': 28528573,
    #                     'name': 'Rosie Harte',
    #                     'tns': []}],
    #             'artistClassics': False,
    #             'awardTags': None,
    #             'cd': '1',
    #             'cf': '',
    #             'copyright': 1,
    #             'cp': 526012,
    #             'crbt': None,
    #             'displayTags': None,
    #             'djId': 0,
    #             'dt': 210000,
    #             'entertainmentTags': None,
    #             'fee': 1,
    #             'ftype': 0,
    #             'h': {'br': 320002,
    #                   'fid': 0,
    #                   'size': 8403113,
    #                   'sr': 44100,
    #                   'vd': -73777.0},
    #             'hr': None,
    #             'id': 508671230,
    #             'l': {'br': 128002,
    #                   'fid': 0,
    #                   'size': 3361271,
    #                   'sr': 44100,
    #                   'vd': -69841.0},
    #             'm': {'br': 192002,
    #                   'fid': 0,
    #                   'size': 5041885,
    #                   'sr': 44100,
    #                   'vd': -71263.0},
    #             'mainTitle': 'Peeping Tom ',
    #             'mark': 17180139520,
    #             'markTags': [],
    #             'mst': 9,
    #             'mv': 0,
    #             'name': 'Peeping Tom (Original Mix)',
    #             'no': 1,
    #             'noCopyrightRcmd': None,
    #             'originCoverType': 0,
    #             'originSongSimpleData': None,
    #             'pop': 100.0,
    #             'pst': 0,
    #             'publishTime': 1396022400007,
    #             'resourceState': True,
    #             'rt': None,
    #             'rtUrl': None,
    #             'rtUrls': [],
    #             'rtype': 0,
    #             'rurl': None,
    #             's_id': 0,
    #             'single': 0,
    #             'songFeature': None,
    #             'songJumpInfo': None,
    #             'sq': {'br': 1054753,
    #                    'fid': 0,
    #                    'size': 27687286,
    #                    'sr': 44100,
    #                    'vd': -73777.0},
    #             'st': 0,
    #             't': 0,
    #             'tagPicList': None,
    #             'v': 53,
    #             'version': 19},
    #            {'a': None,
    #             'additionalTitle': '(Radio Edit)',
    #             'al': {'id': 2880330,
    #                    'name': 'Wicked Wonderland',
    #                    'pic': 109951163118669945,
    #                    'picUrl': 'https://p2.music.126.net/-ea5yMonWQ8D-MpwAeKTbQ==/109951163118669945.jpg',
    #                    'pic_str': '109951163118669945',
    #                    'tns': []},
    #             'alia': [],
    #             'ar': [{'alias': [], 'id': 962293, 'name': 'Tungevaag', 'tns': []}],
    #             'artistClassics': False,
    #             'awardTags': None,
    #             'cd': '1',
    #             'cf': '',
    #             'copyright': 1,
    #             'cp': 665010,
    #             'crbt': None,
    #             'displayTags': None,
    #             'djId': 0,
    #             'dt': 217270,
    #             'entertainmentTags': None,
    #             'fee': 1,
    #             'ftype': 0,
    #             'h': {'br': 320000,
    #                   'fid': 0,
    #                   'size': 8693595,
    #                   'sr': 44100,
    #                   'vd': -62935.0},
    #             'hr': None,
    #             'id': 28694864,
    #             'l': {'br': 128000,
    #                   'fid': 0,
    #                   'size': 3477464,
    #                   'sr': 44100,
    #                   'vd': -59006.0},
    #             'm': {'br': 192000,
    #                   'fid': 0,
    #                   'size': 5216174,
    #                   'sr': 44100,
    #                   'vd': -60443.0},
    #             'mainTitle': 'Wicked Wonderland ',
    #             'mark': 17180139520,
    #             'markTags': [],
    #             'mst': 9,
    #             'mv': 339617,
    #             'name': 'Wicked Wonderland (Radio Edit)',
    #             'no': 1,
    #             'noCopyrightRcmd': None,
    #             'originCoverType': 1,
    #             'originSongSimpleData': None,
    #             'pop': 100.0,
    #             'pst': 0,
    #             'publishTime': 1403625600000,
    #             'resourceState': True,
    #             'rt': None,
    #             'rtUrl': None,
    #             'rtUrls': [],
    #             'rtype': 0,
    #             'rurl': None,
    #             's_id': 0,
    #             'single': 0,
    #             'songFeature': None,
    #             'songJumpInfo': None,
    #             'sq': {'br': 1032096,
    #                    'fid': 0,
    #                    'size': 28030507,
    #                    'sr': 44100,
    #                    'vd': -63012.0},
    #             'st': 0,
    #             't': 0,
    #             'tagPicList': None,
    #             'tns': ['诡丽仙境'],
    #             'v': 142,
    #             'version': 108}]}